

server.tomcat.max-threads: 4

logging:
  com.self.springboot.learning.carpark: INFO

spring.main.banner-mode: 'off'
spring.output.ansi.enabled: always

spring:
  main:
    web-application-type: servlet
  #   MVS none or servlet
  application:
    name: carpark
  profiles:
    # MVS server
    active: server
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"

